set_property SRC_FILE_INFO {cfile:{C:/Users/petra/Documents/Estudios/Grado en Ingeniería Electrónica Industrial y Automática/4º Curso/Primer Cuatrimestre/Sistemas Electrónicos Digitales/Software/Vivado/Nexys4DDR_Master.xdc} rfile:{../../../../Documents/Estudios/Grado en Ingeniería Electrónica Industrial y Automática/4º Curso/Primer Cuatrimestre/Sistemas Electrónicos Digitales/Software/Vivado/Nexys4DDR_Master.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {x}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {y}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVCMOS33} [get_ports {s}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {m}]
